# Generated by Django 3.2 on 2022-06-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220526_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=250)),
                ('currency', models.CharField(default='₹', max_length=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.websites')),
            ],
        ),
    ]
