# Generated by Django 3.2 on 2022-06-04 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsearchresult_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsearchresult',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
