# Generated by Django 3.2 on 2022-06-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productpricechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricechange',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
