# Generated by Django 3.2 on 2022-06-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productpricechange_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availabity',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='availabity_messsage',
            new_name='availability_message',
        ),
    ]
