# Generated by Django 3.2 on 2022-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='tweets'),
        ),
    ]
