# Generated by Django 3.2 on 2022-07-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_sub_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('topic_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorial')),
            ],
        ),
    ]
