# Generated by Django 3.2 on 2022-07-28 11:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialtopic',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
