# Generated by Django 3.2 on 2022-07-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_tutorialtopic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialtopic',
            name='next_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='tutorials.tutorialtopic'),
        ),
        migrations.AddField(
            model_name='tutorialtopic',
            name='previous_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='tutorials.tutorialtopic'),
        ),
    ]
