# Generated by Django 4.0.4 on 2022-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
