# Generated by Django 4.0.4 on 2022-04-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feature',
            new_name='featured',
        ),
    ]
