# Generated by Django 4.0.4 on 2022-04-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categoryies',
        ),
    ]
