# Generated by Django 3.2 on 2022-04-16 08:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_categoryies_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contet',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
