# Generated by Django 3.2 on 2022-04-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20220419_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='pub_date',
        ),
    ]
