# Generated by Django 3.2 on 2022-05-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='posts.Category'),
        ),
    ]
