# Generated by Django 3.2 on 2022-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20220513_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=10, help_text='Read time in minutes'),
            preserve_default=False,
        ),
    ]
